### ISSUE TITLE
New App Icon

### ISSUE THREAD

**Issue by trymeouteh** [tobykurien/WebApps#141]
I wan to suggest this as the icon for WebApps, a round version of the current icon. If this icon is used, no need to credit me especially since it just a modified version of the current one.

https://i.postimg.cc/7L4pskFp/WebApps.png

**Comment by tobykurien** [comment]
Thanks. Unfortunately that image is quite aliased. I can re-generate the same icon as a circular icon using the Android tools. I have been reluctant to, because the black edges may disappear into a dark background. Perhaps it needs a whole new design depicting security or privacy?

**Comment by FabianOvrWrt** [comment]
I've been using WebApps since last year that I got a new phone. This app is great, so I decided to redesign the icon a few days ago. So this is what I came up with.

![V3 Classic2](https://user-images.githubusercontent.com/6712155/61572063-3e470400-aa5e-11e9-8b45-0930e257b702.png)
I tried to give it a more refined style, and also incorporate some gradients in a darker yellow.

![V3 Classic](https://user-images.githubusercontent.com/6712155/61572075-5fa7f000-aa5e-11e9-822a-7137b59dc364.png)
This is the same idea but with inverted colors.

![V3](https://user-images.githubusercontent.com/6712155/61572083-70586600-aa5e-11e9-94c6-f27c4937c4c9.png)
To be honest, that yellow color you use doesn't look good for me, so I also played around with some colors and came up with this gradient. This colors make the app look more refined and secure.

The icon is meant to be adaptive, so it can adapt to any shape (although I don't know how Android does this. Anyway, I hope you like this icon and thanks for developing this app!

**Comment by tobykurien** [comment]
I like the shield motif in the middle. Maybe we can do away with the world map underneath to simplify it. I like the blue gradients - it would be good to get some opinions from other regular users.

**Comment by FabianOvrWrt** [comment]
Well, without the map behind it may look a bit too simple. Maybe using a wave-like shape for "surfing the web" may be a way to define the app. Or using a more simple "world" symbol to draw attention that this behaves like a web browser, or maybe you have a better idea to fill the background of the icon, because the shield by itself says to little about what the app is capable of.

**Comment by tobykurien** [comment]
I agree with your points. Not sure what option would be best, most of the good app icons on FDroid are simple and round, so perhaps use them for inspiration.
