### ISSUE TITLE
Certification Acceptions Are Not Saved

### ISSUE THREAD

**Issue by puppykickr** [tobykurien/WebApps#150]
It seems that almost every WebApp I have keeps getting these certification warnings over and over.

I keep tapping 'Accept' to no avail.

Is it possible to make this 'feature' able to be switched off for the devices that it seems to not work on?

ZTE 558VL
7.1.1
apk version 2.23

**Comment by puppykickr** [comment]
I will test it further, and screenshot if it occurs more.

I currently use two devices, so I will see.

**Comment by puppykickr** [comment]
Happened again early this morning while checking e-mail.

i took screenshots, but for some reason Google Drive wont let me upload them.  I am in the process of moving all my cloud info off of Google and onto Telegram anyway.  #googlesux

If you have an email or some other way for me to send them let me know.
If you have Telegram, that would be the best.

Here is a link o the screenshots on Telegram:

https://t.me/joinchat/AAAAAE4n2HyqqjSU-3ezHg

**Comment by tobykurien** [comment]
Thanks, I see the screenshots. It is because you are being redirected from mail.google.com to accounts.google.com (and then probably back again), and each domain has a different certificate. These kinds of problems are common across Google web apps, which is why I created a whole app for handling just Google web apps called GApps: https://github.com/tobykurien/GoogleNews

Actually Web Apps is a fork of GApps.



On September 18, 2019 9:51:06 AM GMT+02:00, puppykickr <notifications@github.com> wrote:
>Happened again early this morning while checking e-mail.
>
>i took screenshots, but for some reason Google Drive wont let me upload
>them.  I am in the process of moving all my cloud info off of Google
>and onto Telegram anyway.  #googlesux
>
>If you have an email or some other way for me to send them let me know.
>If you have Telegram, that would be the best.
>
>Here is a link o the screenshots on Telegram:
>
>https://t.me/joinchat/AAAAAE4n2HyqqjSU-3ezHg
>
>
>
>
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebApps/issues/150#issuecomment-532565343

-- 
tobykurien.com | @tobykurien

**Comment by puppykickr** [comment]
Thank you so much for the explanation.

I actually have Gapps on an identical device that I use for media viewing and storage, and haven't tried it out yet.

Perhaps I should include it onto the devices that I use for such things.

**Comment by puppykickr** [comment]
Wow.
Gapps is great.
Thank you so.much.
I hate to deal with Google at all, but you have made it much better.
