### ISSUE TITLE
Cookies are passed between sandboxes

### ISSUE THREAD

**Issue by orencio** [tobykurien/WebApps#3]
Hi. When I save a web site (for example https://mail.google.com) and I authenticate in it, after create a new sandbox for other site (for example https://www.Google.com) the session is passed from the first sandbox to this one.

Is this correct there is a problem? I thought that every sandbox had it own cookie space and sessions weren't transmitted between they.

**Comment by rigid** [comment]
Cross-sanbox cookies don't sound too good, since cookies are state-of-the-art for profiling users' browsing habits.
I found this http://lackingrhoticity.blogspot.de/2011/02/cookies-versus-chrome-sandbox.html (regarding the Chrome Sandbox, but maybe it's still useful)
I wouldn't claim myself a web-dev expert, but maybe one of my ideas are useful:

* for every sandbox, create a new user profile in the background (if possible with webkit ?)
* before leaving a sandbox, save all cookies and store them separatly "per-sandbox". When entering a new sandbox, clear all cookies and restore the saved ones?
* "convert" cookies from/to web-keys on the fly to store cookies in history URLs? (surely, this is a bad idea :)

I hope this issue can be solved in some way.

**Comment by tobykurien** [comment]
Thanks @rigid the idea of saving and restoring cookies per webapp sounds like a good one, I'll re-open this issue and see if I can implement something like that.

**Comment by rigid** [comment]
oh great! I'm looking forward to it! :tada:

**Comment by tobykurien** [comment]
I have implemented a "brute-force" sandboxing mechanism for Android KitKat+. Could you please test it? A build is available here: http://tobykurien.com/tmp/WebApps.apk

Essentially what it does is to rename the webview data folder for each webapp you save, i.e. each webapp has it's own cache and data directories, as it was in older versions of Android. There is a downside to this: you won't be able to login any website that uses redirection to another domain to login (e.g. Google). Also, you will have to re-login to all your current webapps when you upgrade, since they start with a clean slate.

**Comment by tobykurien** [comment]
Actually, hold tight, found some issues with the cookie handling and caching.

**Comment by allo-** [comment]
What about deleted sandboxes? Cookies seemed to persist.

steps to reproduce:

- Create a mobile.twitter.com sandbox
- Login
- Remove sandbox
- Create the sandbox again

**Expected:** You're logged out
**What happened:** I was still logged in

A manual "delete this sandbox' cookies" button would be a nice idea as well. So you can be sure if you're logged out.

**Comment by tobykurien** [comment]
A new implementation of cookie handling has been implemented as suggested by @rigid - cookies are saved to the database on page load, and restored when the webapp is re-opened, with all other cookies being deleted. To make sites like Twitter work, all cookies are saved to the root domain (twitter.com) and then made available to any subdomain (api.twitter.com, mobile.twitter.com, etc).

This cookie implementation also solves the problem that deleting a webapp leaves cookies behind. However, cached files and local storage will remain behind.

Finally, this also solves #48 as you can now save more than one instance of an app with separate cookies.
