### ISSUE TITLE
v2.15 not building for F-droid

### ISSUE THREAD

**Issue by kabo** [tobykurien/WebApps#90]
It seems that v2.15 isn't building on fdroid

https://f-droid.org/wiki/page/com.tobykurien.webapps#v2.15

**Comment by tobykurien** [comment]
I don't understand, the linked build log says it succeeded?

**Comment by kabo** [comment]
If you look at the history for the build log there's an error there

https://f-droid.org/wiki/index.php?title=com.tobykurien.webapps/lastbuild_22&oldid=212881

**Comment by tobykurien** [comment]
Thanks @kabo the error log doesn't make sense to me unfortunately. I changed the code structure of the app, and it seems maybe F-droid stores some configuration information about the app that needs to be updated? The exact same gradle build commands as before still work, which is why I don't see anything I could change to make the build work.

**Comment by tobykurien** [comment]
Looks like the build worked. I got v2.15 via F-droid
